baseURL = "https://papnori.github.io/"
languageCode = "en-us"
title = "Nora Pap"
theme = "PaperMod"

[params]

  author = "Nora Pap"
  description = "AI Engineer • Co-founder of Skinsight"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  homeSections = ["posts"]

  socialStyle = "rounded"
  socialColor = true




